<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/TOKENIZATION_OF_SPAM_HAM_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
df = pd.read_csv("SMSSpamCollection",sep="\t",names=["Label","Text"])
df.head(10)

  Label                                               Text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [8]:
df["Label"]=df["Label"].map({"ham":0,"spam":1})

In [9]:
df.head()

   Label                                               Text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.head()

   Label                                               Text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [11]:
x = df["Text"]
y = df["Label"]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
#First conversion to tokens and then to numbers which will be easily understood by comp!!

In [17]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokens = Tokenizer(num_words=50000)

In [18]:
print(tokens)

<keras.src.legacy.preprocessing.text.Tokenizer object at 0x796c06700e90>

In [19]:
tokens.fit_on_texts(x_train)

In [20]:
x_train_new = tokens.texts_to_sequences(x_train)

In [21]:
x_test_new = tokens.texts_to_sequences(x_test)

In [22]:
print(x_train_new)

[[87, 2, 172, 485, 461, 121, 33, 5, 3857, 3858, 315, 1268, 30, 2603, 67, 82, 2, 1657, 2, 316, 238], [246, 873, 15, 54, 8, 462, 160, 21, 25, 95, 1658, 77, 1, 61, 1120, 3859, 33, 174, 3, 53, 2604], [48, 58, 3860, 49, 85, 97, 99, 59, 6, 247, 99], [122, 2605, 428, 22, 39, 1445, 166, 23, 208, 4, 1121, 62, 59, 48, 28, 1, 599, 5, 1446, 2605], [463, 1122, 3, 874, 50, 52, 62, 2606, 3861, 35, 4, 46, 799, 668, 113, 49, 2, 874, 669, 18, 1123, 2, 82, 1659, 524, 3862, 87, 82], [935, 8, 800, 239, 12, 670, 2, 32, 54, 15, 11, 1660, 25, 1, 28, 109, 4, 801], [317, 339, 6], [194, 13, 96, 38, 3863, 64, 324, 4, 802, 445, 671, 1019, 171, 18, 1269, 2607, 936, 41, 9, 100, 486, 547, 2, 221, 3, 16, 2010, 2608, 3864, 2011], [383, 23, 86, 78, 202, 126, 286, 110], [1661, 875, 325, 59, 28, 1270, 240, 803], [122, 6, 86, 29, 5, 804], [119, 2609, 1662, 384, 39, 109, 144, 75, 1662, 876, 29, 1124, 88, 227, 241, 1447, 548, 28], [47, 88], [36, 3, 86, 505, 2610, 5, 2611, 105, 174, 10, 53, 25, 1, 28, 49, 2, 5, 242, 1, 195, 14, 2, 32, 5, 2612, 145], [805, 60, 23, 1020], [6, 17, 4, 806, 1125, 937, 135, 877, 6, 91, 25, 248, 16, 2613, 2, 636, 54, 87, 937, 82, 114, 209, 228, 125, 1663, 1664, 186, 2614], [2012, 36, 3, 3865, 524, 2615, 14, 1448, 5, 268, 1126, 3866, 2013, 340, 3867, 2014, 3868, 5, 1021, 115, 80, 3869, 1665, 2616, 575, 3870, 1449, 8, 1450, 1666, 3871, 3872, 464, 330, 2015, 464, 75, 60, 2012], [16, 3873, 807, 2, 3874, 2013, 287, 255, 78, 18, 8, 5, 402, 154, 22, 1667, 3875, 38, 75, 1022, 13, 3876, 1451, 1668, 210, 2016, 3877, 3878], [231, 9, 180, 1, 306, 446, 2, 97, 3, 111, 15, 41, 231, 9, 180, 31, 25, 1127, 35, 3, 7, 18, 2617, 71, 15, 243], [121, 20, 3, 45, 600, 3, 403, 110], [119, 157, 7, 11, 1669, 37, 3879, 54, 5, 2618], [119, 348, 1, 326, 21, 64, 13, 549, 3880, 21, 37, 550, 25, 123, 120, 1452, 22, 938, 7, 5, 1128, 1271, 64, 5, 232, 18, 4, 3881, 1129, 3, 195, 10, 878, 21, 48, 3, 225, 18, 13, 549, 119, 7, 293, 13, 170, 49, 35, 3, 12, 21, 2619, 35, 13, 3882], [879, 3, 2620, 15, 1670, 7, 880, 27, 17, 4, 672, 487], [1671, 447, 32, 13, 808, 202, 2, 2621], [1453, 6, 116, 47, 160, 331, 144, 2622, 29, 3883], [703, 53, 74, 9, 385, 939, 8, 940], [38, 24, 941, 465, 1272], [1023, 84, 37, 2, 294, 21, 3, 94, 341, 881, 10, 42, 551, 29, 362, 2623, 50, 1454, 211, 21, 30, 47], [637, 88], [552, 2624, 112, 553, 112, 6, 91, 23, 882, 24, 1, 28, 363, 95, 32, 2625, 287, 35, 2017, 38, 120, 1273, 6, 91, 244, 11, 112, 233, 704], [809, 554, 79, 269, 15, 52, 3884, 15, 1274, 278], [63, 1024, 4, 2018, 146, 4, 555, 36, 39, 234, 1275, 135, 2, 63, 59, 158, 211, 30, 123, 3885, 24, 59, 942, 2626], [488, 222, 11, 2019, 3886], [2020, 3887, 3888, 1276, 27, 3, 32, 5, 3889, 3890, 203, 2627, 145, 33, 30, 8, 65], [176, 68, 1, 318, 2, 232, 150, 44, 43, 25, 66], [1, 386, 127, 60, 525, 21, 2021, 10, 181, 31, 161, 2021, 136, 3, 638, 263, 187, 2, 204, 2628, 83, 270], [288, 146, 29, 2629, 1, 505, 746, 1672, 19, 747, 270, 803], [1277, 671, 248, 506, 556, 15, 2630, 1277, 576, 2, 30, 212, 37, 557, 40, 429, 943, 319, 22, 67, 1277, 2, 705, 120, 673, 139, 2631, 342, 183], [883, 320, 128, 34, 1278, 706, 15, 1025, 576, 89, 69, 130, 2, 1455, 22, 810, 1279, 884, 96, 175, 307, 810, 1456, 2022, 811, 1026, 2023, 259], [60, 3891, 944, 3892], [3893, 11, 707], [119, 812, 2632, 3, 332, 319, 21, 507, 404, 229, 5, 945, 7, 31, 5, 3894, 3, 140, 10, 4, 2633, 7, 79, 140, 3, 75], [2024, 2, 30, 3895], [31, 161, 84, 1, 601, 177, 558, 19, 27, 41, 708, 127, 6, 28, 184, 117, 3896, 127, 885, 3897, 78, 47], [55, 178, 155, 3898, 50, 2634, 7, 3899, 33, 23, 30, 558, 2, 58, 2, 402, 89], [34, 159, 886, 9, 813, 506, 556, 2, 1280, 34, 159, 8, 22, 67, 159, 2, 705, 66, 196, 125, 1281, 1130, 364, 343, 2025, 2026, 2027, 1673], [119, 21, 64, 4, 946, 147, 1, 326, 3, 67, 21, 2, 10], [106, 140, 90, 11, 182], [126, 15, 165, 247, 3900, 9, 23, 887, 9, 14, 525], [122, 27, 3, 70, 187, 2, 188], [709, 674, 238, 1282, 2028, 3901, 2635], [28, 3, 318, 2029, 2030, 12, 602, 3, 67, 165, 197, 12], [264, 127, 73, 28, 363, 5, 1674, 1457, 710, 748], [38, 639, 944, 270, 223, 31, 46], [79, 30, 29, 800, 8, 57, 44, 43, 2636], [198, 104, 15, 577, 35, 2637, 340, 197, 603, 15, 11, 711], [888, 42, 34, 96, 35, 4, 46, 526, 675, 15, 1675, 37, 69, 170, 2, 2031, 59, 176, 295, 32, 4, 526, 2638, 2639, 250, 199, 40, 120, 669, 259, 811, 295, 3902], [89, 61, 78, 2, 712, 25, 61, 23, 558, 2, 3903, 5, 279], [16, 1283, 814, 2032, 2640, 22], [676, 7, 2033, 527, 3904, 17, 578, 72, 815, 676, 1284], [50, 2034, 947, 3905, 271], [130, 74, 17, 55, 3906, 341], [1, 61, 131, 48, 20, 3], [9, 3907, 189, 1676, 3908, 55], [3909, 365, 89, 1, 265, 136, 2, 32, 120, 3910], [28, 4, 23], [31, 245, 148, 38, 84, 1, 211, 24, 71, 889, 61, 1027, 2, 2641, 83, 62, 84, 213, 20, 3, 948, 18, 1028], [38, 349, 35, 5, 2642, 1, 350, 27, 14, 154, 508, 24, 1, 95, 53, 203, 466], [3, 20, 4, 164, 164, 164, 164, 448, 333, 26, 1285], [106, 430, 28, 3, 387, 166, 10, 29, 5, 3911, 18, 3912, 14, 149, 30, 154, 18, 5, 153], [79, 80, 24, 2035, 157], [106, 106, 111, 248, 89], [116, 6, 890, 5, 3913, 1458], [1, 61, 239, 2036, 16, 10, 351, 3, 46], [130, 14, 1131, 8, 54, 15, 2643, 2644, 190, 2645, 1459], [84, 56, 4, 243, 334, 528, 18, 5, 153], [1286, 467, 14, 33, 58, 224, 89, 27, 71, 1, 162, 3914, 1287, 7, 2646], [816, 431, 1, 559, 4, 2647, 15, 1029, 2, 173, 205, 3915, 37, 1460, 79, 86, 559, 4, 2647, 949, 26, 1677, 80, 3, 142], [73, 1678, 3916, 3917, 89], [2648, 256, 5, 191, 62, 6, 162, 6, 529, 10, 468, 817, 36, 1, 529, 6, 191, 3, 27, 63, 10], [31, 65, 7, 1, 28, 80, 3, 24, 3, 214, 80, 10, 388, 3, 149, 3918, 2037, 1, 891, 5, 1288], [102, 11, 818, 155, 18, 11, 153, 2, 1289, 7, 39, 17, 37, 107, 2649, 352, 72, 371, 2650, 7, 17, 4, 321, 3919, 155, 161, 560, 6, 51, 17, 6, 107, 42, 2, 405], [47, 88, 1, 2651, 19, 49, 2038, 2039, 40, 4, 449, 19, 1132, 950, 6, 241, 19, 67, 10, 65, 26, 151], [112, 3920, 1, 61, 604, 2, 1290, 1030, 12, 117, 3921, 2040, 105, 27, 173, 8, 640, 29, 44, 605, 43, 1291], [206, 3, 366, 14, 1031, 130, 79, 559, 14, 8, 170], [217, 141, 3922, 100, 674, 238, 7, 951, 13, 108, 311, 115, 749, 3, 2, 184, 54, 135, 14, 9, 16, 50, 406, 3923, 3924], [122, 3, 56, 111, 489], [222, 1276, 18, 3925], [385, 3926, 509, 151, 465, 6], [194, 39, 20, 296, 2, 221, 3, 167, 1292, 297, 367, 21, 3, 17, 212, 4, 1461, 171, 272, 16, 3927, 128, 469, 3928, 510, 3929, 66], [207, 1133, 77, 819], [1, 63, 6, 19, 11, 389, 3930, 2652, 1, 61, 84, 24, 1, 63, 6], [3931, 2653, 35, 1271, 145, 44, 43, 12, 820, 44, 606, 43, 141, 107, 2041, 2, 5, 3932, 450, 18, 44, 43, 29, 44, 62, 43, 44, 43], [112, 39, 56, 44, 43, 2042, 102, 102], [312, 16, 6, 1462, 29, 3933, 35, 11, 511, 21, 3934, 2043, 3935, 432, 82, 2044, 10, 19, 448, 1679, 106, 1031], [24, 61, 78, 2, 712, 390, 51, 2, 27, 20, 554, 312, 58, 65, 14, 1134, 390], [36, 6, 227, 641, 59, 48, 1, 49, 19, 512], [4, 2045, 1463, 2046, 57, 44, 43, 4, 362, 3936, 9, 3937, 470, 7, 1135, 3, 821, 4, 750, 713, 2045, 12, 44, 43], [56, 3938, 3939, 75, 391, 1293], [3, 20, 23, 3940, 10, 24, 3, 17, 2, 1032, 11, 1680, 105], [1136, 57, 2047, 1681, 3941, 42, 352, 203, 1021], [280, 73, 241, 2, 49, 65, 133, 952], [11, 549, 64, 47, 24, 391, 3942, 88, 1464, 1033, 89, 24, 146, 47, 40, 10, 181, 31, 23, 677, 111, 2654, 24, 386, 3943, 18, 11, 883, 885, 751], [32, 5, 1294, 892, 579, 372, 26, 490, 953, 18, 1682, 96, 12, 2655, 507, 69, 235, 26, 953, 2, 1683, 1465, 81, 1684, 82, 1685, 1686, 313, 209], [48, 20, 3, 156, 127, 752, 1687, 8, 12, 5, 103, 407, 251, 37, 2656, 3, 4, 672, 68], [126, 260, 70, 10, 2, 641, 1034, 3944, 383, 109, 4, 449], [1, 530, 6, 403, 339, 74, 162, 175, 2048], [102, 65, 39, 17, 22, 2049, 2657, 100, 642, 211, 30, 131, 19, 133, 6, 36, 6, 1688, 58, 42], [2658, 9, 29, 44, 62, 43, 61, 23, 11, 1466, 6, 94, 807, 1, 247, 6, 1689], [2050, 1690, 822, 3945], [119, 1467, 9, 41, 5, 191, 62, 6, 318, 524, 753, 15, 607], [1, 491, 42, 298, 823, 160, 433, 51, 314, 249], [2051, 37, 1295, 10, 21, 3, 2052, 100, 1691, 182], [69, 893, 2, 3946, 2, 471, 13, 2053, 874, 889, 3947, 1692, 434, 66, 299, 13, 408], [16, 10, 1, 435, 1468, 2, 1282, 575, 166, 3948, 7, 1035], [373, 40, 2659, 92, 714, 224, 18, 10], [289, 79, 69, 3, 8, 4, 335], [223, 164, 192, 30, 308, 18, 1469], [1, 247, 13, 145, 2, 2660], [3949, 48, 6, 2661, 127, 34, 47, 530, 83, 6, 1137, 63, 85, 168, 109, 186], [79, 174, 3, 53, 45, 14, 2662, 8], [754, 13, 1296, 450, 824, 12, 3950, 367, 2663, 2664, 671, 678, 2, 128, 16, 3951, 825, 469, 3952, 755], [51, 23, 1138, 2054], [1, 76, 531, 1, 306, 49, 185], [9, 65, 111, 509, 1470, 1, 28, 49, 2, 7, 374, 826, 1139, 7, 37, 436, 351], [38, 60, 3953, 15, 827, 3954], [608, 19, 96, 1693, 1694, 91, 492, 16, 2665, 22, 1695, 609, 34, 828, 319, 1696, 679, 1697, 2666, 472, 1698, 1699, 1297, 1298, 1299, 1300], [170, 1, 947, 3, 33, 3, 273, 3955], [2055, 1471, 715, 3956, 2667], [48, 2056, 3, 643, 11, 610], [130, 353, 1, 76, 2, 3957, 644, 13, 2057], [493, 36, 229, 193, 174, 10, 53, 45, 229, 604], [954, 680, 756, 1301, 172, 4, 603, 894, 1036, 681, 36, 6, 53, 231, 1140, 5, 2668, 9, 8, 81, 1700, 2, 1141, 313, 209, 1037, 1701], [181, 955, 148, 73, 1702, 829, 25, 1, 169, 73], [39, 23, 604, 270, 47, 88, 59, 39, 49, 2058, 85, 368, 6, 269], [38, 76, 331, 386, 3958, 144, 108, 830, 433, 409, 23, 710, 1, 269, 10, 239, 40, 11, 645, 19, 317, 2059, 25, 1, 28, 956, 227, 1142, 6, 339, 6, 1703, 34, 340], [256, 289, 1472, 30, 110, 52, 118, 1038, 53, 45, 229, 218], [410, 52, 488, 1704, 1, 580, 1143, 344, 15, 3959, 3960, 8, 10, 76, 2, 436, 4, 473, 25, 30, 14, 274, 3961, 173, 10, 78, 7, 71, 6, 162, 1039, 21, 1, 32, 5, 341, 2, 32, 202, 5, 268], [130, 1473, 8, 831, 392, 206], [411, 29, 5, 336, 3962, 86, 65, 36, 3, 28, 2669, 42, 126, 3963, 7, 70, 2, 140, 5, 103, 3964, 4, 273], [60, 4, 412, 15, 957, 2060], [39, 375, 160, 39, 29, 958, 22], [11, 1474, 9, 2670, 170], [142, 1, 61, 23, 78, 2, 1470, 25, 1, 28, 58, 2061, 6, 16, 10, 97, 10, 121, 7, 45, 2, 58, 142], [39, 56, 4, 2671, 206, 93, 189, 110], [130, 24, 28, 39, 166, 8, 462, 181, 33, 49, 2, 3965, 7, 59, 77, 3, 234, 69, 29, 376, 82, 7, 94, 527, 895, 17, 578, 72, 815, 676, 1284], [110, 9, 11, 103, 511, 3966, 3967, 52, 21, 3968], [297, 3969, 1, 95, 104, 25], [194, 39, 20, 296, 2, 221, 6, 611, 297, 367, 21, 3, 17, 212, 4, 1144, 171, 272, 16, 3970, 50, 682, 300, 128, 3971, 364, 3972], [1, 76, 466, 83, 21, 532, 309], [288, 187, 88, 36, 6, 227, 241, 146, 47], [203, 2062, 342, 9, 8, 1475], [2672, 413, 3973, 3974, 51, 20, 3, 646, 15], [39, 20, 1040, 2, 32, 508, 72, 290, 50, 2673, 3, 86, 42, 12, 462, 215], [46, 125, 32, 3975, 3976, 757, 372, 1476, 46, 37, 87, 49, 2, 41, 147, 154, 22], [116, 6, 184, 54, 51, 62, 5, 376, 9, 29, 531, 1, 76, 2, 873, 126, 286, 54], [805, 2674, 959, 18, 11, 108], [194, 41, 9, 100, 486, 547, 2, 221, 6, 13, 1461, 171, 50, 451, 9, 86, 1477, 494, 2, 128, 16, 22, 2675, 2676], [112, 1, 61, 23, 3977, 13, 607, 98], [34, 78, 19, 1705, 2677, 2678, 7, 437, 2, 4, 287, 647, 2, 128, 581, 1705, 2063, 2679, 159, 275, 66, 2, 636, 54, 81, 219, 2, 2680], [1, 198, 179, 5, 108, 154, 22, 105, 67, 4, 147], [3978, 95, 204, 1706, 1, 28, 1707, 13, 3979, 648, 10, 75, 487, 35, 10, 7, 1, 17, 126, 683, 960, 12, 612, 15, 205, 174, 158, 1478, 213, 16, 10, 637], [84, 79, 16, 101], [47], [946, 50, 3980, 98, 16, 3981, 896, 71, 65, 9, 117, 194, 147, 239, 12, 3], [36, 6, 879, 99, 77, 191, 146, 47, 88, 31, 23, 308, 270], [47, 88, 26, 6, 241, 10, 49, 393, 40, 6], [161, 55, 3982, 2681, 351, 213], [119, 129, 133, 6, 101], [122, 12, 10, 65, 9, 38, 257, 18, 708, 220, 1, 33, 169, 11, 3983, 7, 97, 3], [613, 428, 6, 649, 9, 14, 3, 581, 2064, 2682, 614, 159, 26, 485, 1479, 758, 16, 22, 2683, 961, 364, 343, 2684, 2685, 377, 394, 96, 1480], [129, 5, 3984, 473, 9, 44, 43, 1481, 174, 10, 53, 36, 45, 48, 123, 3, 70], [23, 161, 615, 17, 38, 260, 31, 2065], [29, 51, 62, 20, 3, 276], [897, 1, 369, 378, 71, 129, 109, 114, 370], [194, 41, 9, 100, 486, 547, 2, 221, 6, 13, 1461, 171, 50, 451, 9, 86, 1477, 494, 2, 128, 16, 22, 2675], [21, 1041, 2686, 3985], [1, 67, 5, 2687, 3986, 92], [106, 7, 229, 193, 1, 94, 17, 2, 17, 3987, 2688, 2, 27, 14, 266], [182, 12, 5, 1482, 22, 2066, 2067, 35, 5, 2068, 35, 2069, 18, 13, 96, 12, 4, 46, 1129, 37, 87, 35, 2066, 22], [20, 39, 156, 5, 2689, 142, 1, 317, 37, 4, 40, 2070, 181, 15, 962, 2690, 76, 2, 873, 1483, 286, 54, 29, 126, 1042, 551, 56, 2691, 50, 89, 1708, 495, 316, 815, 25, 1, 345, 32, 1145, 18], [155, 18, 5, 3988, 549, 1, 64, 1146, 36, 13, 1302, 2, 32, 670, 650, 1709, 39, 49, 4, 166, 7, 1484, 684, 15, 2692, 1043], [106, 79, 711, 54, 8, 4, 335, 301, 80, 3, 65], [1, 2071, 3989, 5, 147, 3990, 98], [322, 58, 202, 651, 33, 30, 110, 216], [52, 524, 192, 103, 3991, 7, 5, 66, 249, 1, 28, 1710, 165, 2, 9, 3992, 3993, 3, 8, 800], [580, 10, 2072, 10, 132, 10, 1485, 24, 8, 5, 316, 15, 11, 158, 45, 1, 832, 438, 173, 75, 1486, 18, 11, 2693, 7, 148, 805, 1, 168, 6, 17, 4, 192, 68, 716], [116, 3, 363, 83, 5, 103, 2671, 3994, 14, 561, 35, 52, 15, 3995, 286], [59, 180, 38, 75, 759, 2, 10], [78, 2, 474, 142], [246, 1487, 48, 2073, 60, 110, 72, 5, 153, 155, 55, 107, 18, 19, 1711, 35, 21, 513, 1, 963, 8, 3996, 25, 652, 39, 17, 2, 166, 42, 216, 685, 670, 554], [615, 2694, 12, 2074, 74, 56, 833, 7, 3997, 56, 2695], [3998, 56, 309, 8, 2075, 2076], [25, 180, 475, 3, 1147], [3999, 4000, 4001, 12, 4002, 4003], [98, 257, 41, 2696, 84, 12, 834, 21], [130, 65, 222, 236, 2697], [39, 20, 612, 281, 182], [98, 717, 11, 96, 45, 3, 32, 42, 8, 178], [28, 3, 148, 51, 562], [62, 85, 302, 91, 5, 330, 4004, 278, 8, 100, 158, 1303, 62, 550, 205, 2, 563, 302, 7, 1303, 4005, 302, 550, 205, 2, 563, 62, 233, 1044], [4006, 14, 9, 59, 404], [1304, 548, 882, 151], [94, 132, 158, 137, 4007, 244, 184, 62, 2, 1148, 14, 274, 23, 1045, 496, 2, 13, 158, 24, 1488, 4008, 120, 158, 2, 34, 496, 233, 704, 1149, 718], [354, 88, 4, 282, 497, 137, 59, 280, 227, 6, 49, 77, 476, 19, 232, 89], [129, 564, 23, 4, 395, 15, 278, 1150, 8, 4009, 18, 103, 496, 1489, 126, 4010, 8, 2077, 7, 5, 1046, 4011, 141, 200, 78], [116, 6, 32, 21, 147], [143, 365, 274, 52, 34, 718, 58, 525], [223, 898, 1305, 34, 349], [676, 39, 91, 2698, 110, 117, 1047, 113, 90, 226, 1712, 48, 116, 39, 27, 8, 5, 4012, 41, 414, 102, 2, 7, 7, 133, 6, 216], [1048, 83, 217, 9, 52, 55, 38, 1306, 12, 21], [293, 273, 415, 7, 1, 746, 23, 2, 711, 54], [51, 89, 719, 719, 9, 277, 25, 38, 138], [1, 355, 6, 2699, 123, 6, 2078, 964, 48, 248, 6, 91, 19, 10, 610, 6, 2079, 355, 6, 405], [5, 1490, 4013, 1151, 9, 4014, 2, 4015, 41, 686, 67, 54, 252, 186, 2700], [73, 227, 241, 2, 374, 1713, 2692], [129, 31, 245, 317, 11, 965, 22, 17, 4, 55, 281, 118], [95, 1491, 4016, 45, 452, 224], [24, 31, 18, 4, 1669, 7, 1, 1714, 114, 137, 236, 4017, 15, 1049, 451, 1050, 31, 244, 18, 4, 1669], [281, 27, 3, 410, 10], [38, 453, 454, 529, 453], [39, 17, 195, 2701, 12, 252, 238, 835, 2702, 2080, 2, 34, 489, 582, 12, 466, 221, 205], [4018, 1715, 22, 2703], [51, 1, 616, 9, 27, 115, 58, 2704, 3, 54, 45, 60, 202, 26, 9, 14, 4019, 3, 28, 374, 71, 236, 1139, 71, 3, 70], [84, 79, 16, 101], [1, 1492, 5, 533, 451, 60, 200, 21, 575, 3, 53, 5, 2019, 68, 6, 4020, 45, 33, 32, 2081, 8, 83, 19, 2, 4021, 24, 105, 105, 95, 2705, 1, 53, 6, 91, 966, 105, 1716, 190, 9, 65, 187, 8, 34, 1493, 2082, 6, 76, 2, 97, 10], [47, 299, 91, 6, 65, 8, 77], [60, 55, 895, 184, 4, 153], [89, 11, 1307, 2083, 32, 308, 52, 9, 129, 7, 1, 61, 190, 8, 5, 1035, 129], [31, 646, 21, 720, 366, 2, 58, 12, 686], [23, 123, 37, 126, 4022, 48, 617, 3], [47, 1, 416, 12, 240, 48, 652], [4023, 583, 270, 7, 306, 2084, 1494, 581], [611, 1495, 899, 1152, 35, 2706, 20, 396, 2, 4, 346, 4, 760, 397, 36, 13, 145, 1153, 16, 2707, 2, 346, 13, 760, 397], [505, 4024, 169, 36, 6, 28, 337, 151, 15, 166, 40, 283, 384, 6, 85, 136, 166, 28, 160, 88, 26, 6, 241, 19, 49, 169, 92, 836, 337, 59, 887, 761, 10, 1154], [4025, 45, 6, 20, 8, 63, 114, 6, 57, 1451, 1717, 19, 6, 32, 1718, 121, 6, 80, 5, 261, 15, 13, 4026, 152, 6, 601, 32, 687, 45, 13], [1155, 1, 134, 11, 514, 92, 50, 54], [51, 246, 1305, 4027, 605, 511], [4028, 6, 2661, 1, 1719, 4029, 4030, 1, 247, 6, 211, 16], [127, 3, 20, 555, 131, 105, 1720, 10, 8, 1156], [1, 56, 4, 16, 50, 4, 406, 145, 1, 61, 416, 2, 58, 2, 2708, 2709, 1, 33, 49, 8, 5, 417], [44, 606, 43, 435, 24, 60, 23, 4, 1721, 370, 110, 25, 60, 345, 2, 188, 50, 2085, 26, 4031, 26, 36, 1, 184, 14, 942, 1496, 1, 350, 1147], [954, 1722, 2, 128, 34, 1723, 277, 67, 4, 2710, 1134, 511, 1308, 2, 2086, 18, 205, 199, 364, 343, 2711, 2712, 2713, 2714, 680, 1033, 653, 1309, 82], [7, 82, 284, 117, 833, 325, 3, 32, 2, 2715, 2716, 688, 4032, 7, 4033, 4034], [6, 53, 39, 4035, 29, 2717], [47, 818, 1, 4036, 14, 64, 47, 1, 37, 527, 137, 123, 1, 17, 2, 27, 126, 939, 286, 11, 837, 7, 59, 17, 2, 4037, 213, 24, 3, 28, 16, 10, 65, 618], [194, 13, 96, 145, 141, 107, 324, 35, 4, 654, 171, 272, 16, 2718, 50, 682, 300, 128, 1157, 510, 689, 66, 394], [4038, 819, 110, 749, 4, 255, 26, 2087, 35, 526, 1724, 8, 885, 838, 2, 32, 4039, 42, 37, 87, 967, 22, 46, 19, 474, 1465, 81, 82, 4040], [190, 102, 4041, 4042, 3, 107], [1310, 1497, 142, 74, 1135, 54, 29, 230, 203, 138, 9, 72, 13, 303, 25, 74, 28, 166, 6, 4043], [2088, 25, 2089, 170, 192, 2719, 2, 5, 2720], [388, 4044, 26, 2721, 968, 1725, 5, 242, 882, 11, 303], [256, 280, 1, 162, 146, 448, 327, 52, 144, 1726, 53, 6, 151, 6, 156, 22], [1, 80, 4, 1268, 15, 1051, 2722], [20, 3, 47, 51, 562, 2, 2090, 57, 41], [189, 189, 762, 78, 2, 297, 5, 1676, 150, 236, 496, 8, 1311, 4045, 4046], [102, 127, 3, 134, 4, 55, 68, 17, 4, 345, 118], [21, 1312, 25, 51, 27, 3, 56, 1313, 12, 13, 322, 1052, 1, 61, 13, 322, 1052, 1498, 1], [194, 13, 40, 1314, 1053, 1315, 277, 26, 690, 619, 494, 16, 1499, 22, 1500, 620, 839, 189, 1501, 1502, 1316, 1503, 209, 584, 1504], [6, 387, 306, 2091, 10, 2092], [31, 379, 1690, 822, 1054, 1505], [4047, 2093, 1158, 565, 1317, 255, 22, 1727, 16, 2723, 585, 418, 50, 114, 2094, 210, 1055, 2, 290, 2724, 210, 2725, 2, 82, 439, 16, 1159, 534, 210], [130, 455, 20, 3, 78, 2, 132, 10, 1728], [55, 417, 11, 707, 48, 621, 21, 1506, 110, 7, 65, 68, 116, 3, 32, 21, 840, 4048, 20, 3, 86, 54, 7, 83, 1, 491, 7, 168, 3, 170], [129, 1, 53, 4049, 33, 109, 186, 15, 10, 25, 38, 1318], [1, 433, 586, 57, 227, 535], [31, 29, 2726, 163, 4050, 22, 24, 31, 8, 11, 1729, 370, 25, 1, 214, 968, 298, 655], [1056, 4051, 515, 6, 42, 19, 155, 8, 25, 123, 4052, 29, 77, 29, 1057, 4053, 4054, 10, 208, 6, 515, 5, 1319, 4055, 1, 263, 22, 280, 432, 6, 37, 97, 10, 69, 2727, 98, 355, 2728], [2729, 182, 12, 13, 1730, 15, 4, 356, 4056, 50, 2729, 752, 107, 900, 4057, 104, 3, 28, 27, 345, 180, 23, 67, 4, 356, 8, 4, 4058, 4059], [4060, 8, 34, 2095, 4061, 4062], [59, 93, 227, 648, 151], [892, 266, 4063, 95, 168, 5, 4064, 1507, 721, 81, 34, 585, 1507, 2, 1508, 901, 892, 2, 1508, 273, 4065, 2730, 2731, 4066, 902, 4067, 259], [1509, 146, 47], [41, 436, 9, 44, 606, 43, 4068], [429, 347, 1510, 56, 396, 456, 60, 55], [1453, 47, 151, 71, 298, 71, 56, 2732, 28, 160, 151], [130, 1, 1511, 4, 1058, 15, 669, 18, 2733, 564, 86, 688, 691, 137, 31, 37, 1512, 42], [38, 116, 3, 4069, 147, 165, 26, 144, 489], [722, 71, 4, 903, 409, 252, 3, 17, 107, 396, 2, 4070, 1461, 171, 1731, 2, 128, 16, 4071, 128, 469, 4072, 510, 969, 566, 66], [25, 419, 2730, 127, 3, 20, 23, 202, 1320, 13, 4073, 4074, 109, 186, 287, 5, 970], [45, 3, 7, 2096, 263, 35, 279], [357, 1038, 53, 498, 42], [322, 39, 20, 385, 4, 509, 18, 4075], [180, 94, 3, 49, 97, 13, 262, 229, 23, 193, 3, 70, 2, 287, 35, 136, 311, 74, 1732, 137, 123, 59, 971, 566, 2734, 136, 2, 58, 763], [4076, 21, 51, 4, 467, 4077, 1, 345, 58, 59], [431, 1, 67, 21, 4078, 2, 13, 489, 582], [47], [37, 4079, 80, 3, 8, 4, 1058, 344, 44, 152], [20, 6, 1321, 9, 65, 688, 65], [723, 57, 4, 477, 2735, 9, 86, 110, 7, 86, 1513, 31, 935, 18, 5, 4080], [182, 12, 1733, 764, 4081, 3, 1059], [38, 1, 94, 17, 1322, 1734, 587, 4, 321, 1160, 54, 15, 4, 2097, 4082, 2736, 2737, 4083], [4084, 408, 12, 196, 87, 579, 26, 2098, 901, 4085, 114, 1735, 1735, 4086, 19, 157, 152, 904, 4087, 291, 4088, 411, 58, 35, 10, 26, 82, 40, 120, 408, 81, 120], [27, 1, 1, 326, 1, 420, 14, 90, 8, 5, 343], [122, 1, 33, 30, 243, 31, 29, 4089, 76, 2, 656, 1323, 26, 1051], [130, 5, 66, 242, 8, 462, 2, 166, 1514, 2099, 1724, 9, 22, 8, 5, 199, 81, 255, 2, 705, 22, 196, 125], [841, 1, 638, 

In [23]:
print(x_test_new)

[[41, 9, 999, 2960, 36, 6, 1992, 11, 384, 2960, 10, 90, 36, 6, 32, 152, 6, 91, 1350, 291, 6, 91, 424, 6, 91, 25, 875, 1193, 267, 2214, 6], [7, 190, 207, 136, 197, 4, 1058, 625, 1859, 25, 582, 2488, 23, 69, 136, 54, 15, 5, 1046, 588, 12, 2575], [2088, 292, 345, 22, 1, 56, 4, 3178, 224, 10, 4914, 177, 345, 36, 1, 134, 4, 335, 2086, 224, 10, 19, 55, 1549], [1155, 17, 126, 95, 368, 187, 1400, 47], [25, 564, 4, 610, 21, 561, 35, 5, 387, 146, 65, 25, 115, 28, 519, 1167, 1577, 5859, 5859], [7155, 37, 76, 8, 5, 14, 580, 136, 4, 395, 25, 74, 10], [63, 1024, 4, 2018, 146, 4, 555, 36, 39, 234, 1275, 135, 2, 63, 59, 158, 211, 30, 123, 3885, 24, 59, 942, 2626], [11, 7593, 184, 40, 10, 75, 88, 1, 269, 203, 7358, 1, 505, 169, 99, 270, 97, 6, 659, 1, 169, 99], [112, 55, 178, 22, 66, 1, 61, 42], [31, 8, 720], [206, 11, 1338, 9, 677, 1559, 35, 11, 9, 57, 19, 423, 508, 1050], [38, 314, 1267, 635, 5, 3030, 9, 18, 13, 2733, 1641, 1050, 31, 25, 1404, 1, 161, 293, 374, 13, 545, 3, 6283], [31, 499, 136, 22, 1066, 331], [1890, 246, 278, 7201, 391, 49, 2, 477, 1112, 9, 908, 77, 3649, 72, 7, 35, 4443, 4822, 197], [46, 372, 69, 191, 2, 7096, 12, 4, 579, 26, 69, 32, 2, 7096, 12, 4, 525, 235, 271, 6221, 259, 150, 337, 46, 408, 20, 2, 81, 82], [338, 1, 61, 239, 12, 13, 16], [757, 1194, 452, 1939, 73, 57, 710, 588, 387, 23, 10, 11, 1402, 57, 148, 452, 3319, 24, 1, 227, 269, 74, 9, 659, 126, 646, 872, 459, 792, 79, 49], [122, 22, 61, 46, 3, 28, 16, 10], [1765, 35, 5, 315, 9, 429, 6, 581, 172, 26, 629, 399, 2812, 35, 1766, 135, 9, 697, 2, 6, 9, 2813, 36, 6, 629, 6, 629, 36, 6, 172, 6, 86, 629], [59, 6, 49, 90, 1186, 88], [157, 79, 257, 8, 4, 1058, 423, 163, 174, 3, 53, 45, 1, 32, 2, 800], [252, 242, 1, 33, 16, 3], [1688, 27, 31, 78, 2, 29, 7138, 1, 638, 56, 4, 153, 2, 221, 136, 595, 59], [1, 369, 256, 180, 3, 591, 966, 3, 501, 53, 21, 564, 4, 153, 5, 1884, 1375, 7, 31, 391, 193, 3, 1961, 527, 895, 109, 14, 904, 191, 5, 2690, 115, 33, 1986, 45, 13, 6654, 9, 59, 37, 1716, 354, 752, 162, 9, 4, 1014, 2, 527, 24, 1, 350, 173, 18, 3, 42], [41, 9, 5, 486, 62, 39, 17, 583, 19, 221, 6, 6, 17, 212, 5, 1199, 171, 19, 128, 9, 429, 16, 66, 534, 228, 738, 399, 585, 418], [106, 106], [60, 23, 5, 268, 110, 86, 588, 12, 4, 309, 48, 123, 27, 5846, 65], [233, 233, 106, 639, 186, 232, 129, 233, 862], [73, 140, 10, 126, 62, 2, 702, 65], [151, 73, 156, 22], [156, 354, 59, 6, 23, 323, 480, 761, 205], [373, 288, 39, 276, 90, 18, 831, 317, 480, 78, 90, 19, 1596, 22, 62, 528, 3818, 40, 1599, 4, 7299, 89, 127, 895, 535, 236, 120, 2477, 2, 58], [9, 1523, 78, 40, 144, 283], [28, 3, 105, 67, 10, 21, 715, 261, 8], [9, 34, 4428, 19, 92, 2515, 321, 181, 207, 160, 479, 4428, 19, 92, 3446, 2515], [178, 66, 1, 28, 47], [157, 146, 386, 743], [306, 280, 586, 1, 266, 1206, 56, 151, 327, 68, 73, 67, 10, 92, 2549, 198, 138, 75], [357, 895, 711, 54, 8, 4, 335], [1, 3073, 11, 46, 344, 6156, 1712, 788, 548, 28, 73, 169, 488, 2274, 88], [3264, 3, 17, 23, 5, 777, 3, 17, 160, 1719, 12, 1643, 766, 392, 2, 471, 13, 777], [386, 317, 11, 503, 6, 317, 480, 160], [895, 3, 436, 202, 57, 44, 43, 1412, 25, 60, 23, 137, 980], [246, 707, 3697, 31, 560, 3, 89, 1, 57, 2, 67, 3, 4, 2425, 7, 2944, 3, 31, 646, 15, 3, 7, 3, 20, 1010, 782, 421], [659, 1, 317, 11, 283, 59, 1, 49, 2158, 224, 88, 523, 152, 950, 88, 6, 317, 34, 283, 160], [1, 187, 88], [79, 69, 22, 52, 7820, 57, 25, 74, 601, 104, 21, 39, 366], [369, 51, 1111, 3, 53, 7637, 3, 332, 184, 54, 135, 14, 9, 140, 205, 4, 16, 18, 50, 406, 196, 210, 275], [1422, 57, 21, 6925, 3], [1, 61, 8, 402, 851, 5, 2469, 125, 10, 22, 1, 33, 16, 3, 29, 660], [3, 258, 374, 51, 3, 148, 695, 1, 32, 4694, 71, 4], [570, 46, 12, 337, 113, 1607, 201, 235, 40, 34, 538, 176, 113, 37, 81, 201, 2, 570, 32, 1243, 7, 97, 34, 828, 139, 1238, 250, 199, 867, 1894, 2689, 196, 235, 259], [122, 289, 52, 19, 15, 2269, 19, 6, 1517], [1237, 214, 271, 3, 65, 207, 306, 134, 117], [47], [208, 36, 74, 11, 262, 74, 9, 4, 16, 136, 22], [119, 21, 4911, 2, 10, 8, 388, 312, 14, 8, 3018, 45, 60, 54], [37, 948, 13, 529, 16, 11, 112, 663, 27, 17, 4, 672, 68], [46, 111, 68, 24, 1, 317, 29, 291, 18, 1096, 85, 1874], [55, 487, 338, 127, 3, 20, 323, 4, 192, 68, 1, 446, 2, 559, 14, 2, 13, 1888, 21, 1, 17, 107, 243, 8, 1739, 1529, 12, 5, 1493, 335, 1097, 7, 17, 134, 2, 436, 4, 44, 43, 717, 1, 1017, 14, 211, 30, 15, 10, 2, 83, 200, 3, 140, 29, 131, 377, 2, 522, 7, 256, 180, 1, 475, 437, 42, 1, 1815, 61, 8, 4, 7, 432, 30, 558, 2, 436, 5, 717, 41, 460, 11, 2341, 129, 2406, 15, 316, 28, 3, 98, 271, 440, 3, 12, 426], [194, 13, 96, 145, 141, 107, 324, 35, 4, 654, 171, 272, 16, 2718, 50, 682, 300, 128, 1157, 510, 689, 66, 394], [151, 62, 91, 73, 78, 2, 3184], [41, 147, 9, 46, 786, 2, 5, 103, 888, 1624, 731, 2, 745, 50, 41, 238, 87, 82, 844, 196, 275, 66], [102, 127, 6, 32, 41, 81, 3195, 107, 710, 22, 83, 209, 301, 243, 1, 104], [1100, 71, 8, 20, 65, 111, 2615, 12, 10, 1962, 75, 50, 463, 21, 4, 1100, 24, 274, 86, 148, 463, 18, 14], [4302, 1024, 14], [1, 225, 2, 751, 1816], [2305, 21, 3802, 383, 78, 2, 2562, 8, 83, 902], [206, 115, 94, 53, 83, 11, 623, 108, 1, 234, 2127, 7114, 154, 22, 36, 1, 70], [7655, 15, 119, 348, 1446, 4, 513, 4, 355, 2691, 18, 4, 1119, 24, 3550, 18, 99, 711, 3693, 4, 1317, 124], [237, 657, 12, 13, 2382, 69, 1220, 105, 1643, 139, 1405, 541, 1611, 2383, 745, 35, 82, 38, 1047, 717, 271, 2384, 1405, 3822, 3823, 2385], [3, 479, 11, 68, 27, 17, 4, 131, 68, 137], [175, 96, 252, 3, 274, 22, 128, 13, 46, 328, 108, 2758, 4, 436, 49, 1561, 830, 12, 13, 1520, 16, 18, 6221, 6222, 6223, 422, 876, 175, 658, 434], [611, 2111, 899, 1152, 20, 396, 2, 346, 4, 5713, 397, 36, 3, 4, 1063, 98, 16, 1741, 2112, 128, 469, 1742, 1064, 1458], [119, 11, 304, 207, 927, 13, 145, 213, 31, 25, 1404, 69, 10, 90, 41, 844, 1000, 3344, 313, 209], [722, 71, 4, 903, 409, 252, 3, 17, 107, 396, 2, 4070, 1461, 171, 1731, 2, 128, 16, 4071, 128, 469, 4072, 510, 969, 566, 66], [3, 86, 218, 588, 2, 179, 42, 101], [3931, 2653, 35, 1271, 145, 44, 43, 12, 820, 44, 606, 43, 141, 107, 2041, 2, 5, 3932, 450, 18, 44, 43, 29, 44, 62, 43, 44, 43], [47, 109, 34, 62, 85, 299, 34, 480], [122, 48, 621, 14, 110, 8, 4065, 60, 1210, 47, 65, 9, 57, 7, 348, 24, 1, 86, 3805, 6590, 1216], [182, 12, 782, 10, 25, 3, 1059], [207, 1133, 160], [31, 77], [190, 1414, 5, 6362], [13, 226, 2012, 405, 356, 33, 30, 195, 2, 3, 299, 36, 75, 7828, 9, 23, 443, 12, 1137, 69, 90, 5, 2, 32, 5, 226, 356], [391, 47, 24, 4, 282, 1293, 6, 345, 49, 368, 950, 22, 554, 79, 204, 2628], [615, 56, 4, 22, 60, 42, 65], [430, 516, 21, 37, 27, 602, 27, 184, 117, 1364, 2, 30, 8, 1396, 29, 126, 1042, 185, 1903, 470], [38, 4858], [122, 25, 851, 5, 477, 41, 458], [12, 2625, 15, 35, 5, 15, 52, 21, 3, 37, 116, 1192, 17, 4], [119, 1467, 9, 41, 5, 191, 62, 6, 318, 524, 753, 15, 607], [2535, 6, 25, 1196, 249, 1, 140, 6, 11, 822, 106, 6688, 3, 79, 104, 15, 6], [56, 3907, 56, 4, 395, 15, 1579, 48, 2, 148], [2024, 2, 30, 176, 118], [157, 57, 36, 14, 621, 57, 14, 116, 35, 11, 260, 1332, 6808, 11, 348, 8, 57, 362, 117, 483], [982, 25, 833, 3325, 2293, 88, 198, 269, 15, 187, 554, 24, 79, 177, 2059, 11, 1557, 101], [4926, 44, 43], [1, 28, 169, 218, 24, 564, 23, 4, 395, 8, 1116, 15, 4724, 42, 110], [51, 27, 6, 5744, 71, 76, 19, 1588, 6628, 36, 6, 214, 27, 14, 182], [130, 281], [1, 220, 40, 73, 1644, 92, 370, 968], [112, 56, 1820, 7, 7242, 787, 4936, 7242], [25, 9, 1438, 837, 231, 9, 121, 1, 61, 48, 91, 6, 325, 52, 9, 55, 8, 4065, 312, 177, 90, 133, 6, 41, 295, 135, 64, 5, 125, 40, 7858, 2303], [5680, 141, 5681, 162, 4, 2177, 28, 169, 120, 943, 441, 4, 3392, 325, 28, 557, 22, 3, 53, 180, 52, 15, 205, 20, 3152, 1143, 5682, 1821, 789, 836, 5683], [91, 6, 86, 379, 22], [157, 193, 249, 837, 56, 52, 11, 286, 2782, 24, 155, 78, 1457, 457, 12, 72, 5, 153, 135, 9, 41, 95, 53, 145, 1818], [2012, 1303, 8, 158, 60, 980, 2, 1275, 851, 850, 4, 2446, 21, 1122, 4, 302, 26, 5, 924, 21, 1122, 4, 1273], [47, 47, 47, 59, 851, 34, 611, 477], [544, 944, 555, 129], [1056, 1085, 19, 114, 962, 113, 8, 1475, 56, 197, 18, 103, 1412, 630, 24, 1, 64, 115, 222, 4694, 6, 1397, 29, 712, 270, 11, 138, 19, 965], [20, 3, 78, 2, 1098, 1091, 41, 113], [129, 1, 378, 23, 58, 59], [112, 431, 489, 1030, 662, 8, 5, 1077, 431, 484, 3, 1030, 278, 20, 588, 47, 24, 4, 55, 75, 8, 342, 1452], [7655, 15, 5771, 52, 5, 163, 115, 932, 19, 2480, 8, 117, 7587, 115, 458, 115, 247, 327, 5, 479, 72, 1167, 7358, 2661, 52, 54, 15, 124, 399, 66, 114, 475, 1145, 74, 162, 36, 14, 9, 479, 72, 11, 7358, 41, 432, 208, 334, 5771], [1944, 66, 134, 13, 96, 1113, 3, 20, 1229, 2, 484, 2, 5, 336, 490, 328, 96, 12, 46, 16, 5, 96, 484, 250, 46, 18, 2420], [13, 450, 141, 107, 72, 44, 606, 43, 13, 450, 886, 9, 820, 44, 606, 43, 13, 2653, 582, 9, 44, 43], [119, 4, 362, 483, 9, 123, 1342, 8, 441, 6510, 1031, 982, 3, 501, 32, 25, 123, 120, 138, 263, 8, 4, 68, 441, 205, 35, 52, 21, 1047, 62, 938], [1990, 109, 4, 675, 7, 67, 14, 2, 10], [1059, 885, 32, 15, 6445, 3210, 405, 669, 18, 885, 108, 22, 983, 2, 3946, 781, 228, 230, 344, 1331], [189, 31, 385, 14, 8, 287], [338, 1, 76, 592, 15, 3639, 7, 715, 871, 466], [187, 331], [289, 69, 10, 45, 3, 711, 54], [1, 53, 3, 20, 1048, 1785, 24, 1716, 1117, 198, 2438, 1785, 93, 211, 17, 107, 1946, 7, 60, 5478, 36, 93, 741, 443, 2, 5479, 99, 2386, 99, 3255, 33, 5480, 7, 36, 3, 140, 99, 1785, 1554, 22, 93, 33, 37, 1746, 60, 4, 1134, 5481, 5482, 93, 141, 231, 456, 8, 4, 335, 344, 14, 33, 1131, 82], [322, 231, 279, 27, 3, 332, 109, 5, 1787, 447, 279, 9, 567], [193, 36, 1, 32, 117, 50, 3, 21, 146, 7, 3345, 5224, 2, 6416, 4, 1094, 5468], [533, 18, 44, 43, 2293], [303, 1652, 9, 5, 1653, 531, 5, 325, 64, 1651, 18, 44, 43, 1438, 1903, 71, 3767, 277, 52, 3768, 3769, 20, 2006, 1972, 632, 402], [237, 686, 4, 1650, 103, 201, 7308, 9, 42, 40, 686, 89, 686, 9, 46, 19, 474, 109, 412, 81, 201, 2, 1808, 22], [157, 11, 1164, 6970, 54, 15, 462, 24, 7265, 1430, 267, 218, 1, 53], [170, 1, 3, 1, 76, 3, 1, 993, 3, 3697, 31, 25, 735, 468, 3, 170, 1, 63, 3], [143, 103, 251, 11, 38, 114, 325], [122, 269, 39, 537, 49, 2, 151, 39, 1798, 88, 1845, 38, 1627, 18, 831, 181, 564, 944, 123, 739, 2, 49, 36, 39, 3604, 1627, 18, 458], [1, 61, 677, 362, 68, 257, 6247, 1, 61, 23, 129], [26, 388, 11, 1931, 1343, 37, 910, 52, 524, 7, 14, 694, 53, 51, 2, 27], [170, 48, 621, 21, 68, 51, 20, 3, 42, 2, 1, 168, 3, 160, 11, 63, 782, 421, 1, 127, 426, 621, 129], [1647, 2048, 85, 1046, 6758, 1, 269, 1, 133, 73], [6408, 839, 2799, 78, 18], [38, 1318, 127, 3384, 6435, 225, 129, 17, 4, 382, 29], [944, 66, 12, 589, 208, 12, 236, 2436, 93, 9, 358, 1753, 14, 639, 59, 3810, 465, 1513, 941, 1442, 3597, 3810, 9, 5, 5502, 7, 3810, 2073, 111, 349], [1338, 626, 2, 53, 121, 3, 29], [55, 55, 309, 1, 57], [22, 56, 392, 19, 374, 1524, 6, 38, 138, 89], [28, 3, 105, 105, 67, 10, 4, 489, 18, 52, 3, 53, 83, 276, 2, 1985, 110, 52, 3, 53, 83, 1912, 4368, 7, 187, 554, 182], [3, 378, 70, 2, 7775, 54, 120, 37, 8, 798, 7, 37, 477, 18, 23, 3829, 14, 36, 3, 28, 1, 94, 17, 123, 5771, 8, 2096, 7, 240, 4858], [754, 13, 1296, 450, 824, 12, 290, 367, 2663, 2664, 671, 678, 2, 128, 16, 825, 469, 3952, 755, 1435, 2302, 2302], [735], [40, 29, 787, 37, 2, 54, 4, 2552, 477], [39, 23, 385, 509, 160, 1523, 626, 19, 613, 25, 31, 427, 761, 99, 22], [292, 289, 455, 1, 33, 1185, 13, 401, 8, 565, 4141, 835], [4432, 207, 37, 927, 54, 21, 39, 17, 2, 179, 11, 729, 42, 50, 5, 3325, 21, 487, 25, 94, 104, 79, 30, 78, 54, 29, 52, 39, 149, 273, 2, 49, 54, 75, 15, 1438], [598, 142, 306, 561, 45, 14, 561, 146, 160, 89, 8, 5, 15, 598, 142, 94, 1459, 13, 683, 89, 783], [13, 2057, 9, 2522], [38, 24, 895, 27, 1254, 2, 1426], [515, 83, 18, 1712, 573, 1, 61, 152, 59, 24, 66, 495, 424], [51, 145, 27, 6, 287, 29, 9, 14, 779], [157, 256, 5, 1, 56], [102, 818, 1, 317, 29, 152, 27, 6, 114, 19, 179, 10, 42, 26, 166, 10, 69, 90, 18, 41, 145, 355, 1084, 405], [59, 3, 20, 53], [170, 6, 70, 10, 95, 6, 353, 155, 6186, 7, 17, 4, 249, 40, 749, 4, 3699, 62, 35, 4, 526, 1750, 48, 83, 39, 49, 85, 865, 81, 405], [256, 695, 13, 833, 1, 287, 2, 30, 1562], [38, 92, 2472, 78, 2, 310, 8, 6699, 392], [1, 94, 17, 145, 1, 86, 638, 326, 42, 4, 153, 2, 169, 1883], [84, 1, 33, 30, 558, 2, 32, 2, 3, 80, 3, 8, 5, 178], [47, 109, 186, 1209, 2, 3, 137], [1, 70, 126, 2870, 11, 508, 1, 76, 4, 342, 325, 19, 4358, 10, 81, 442, 2, 12, 38, 3422, 81, 82, 19, 316, 81, 7398, 313], [2, 318, 13, 928, 2127, 5, 1123, 1129, 8, 5, 226, 81, 147, 26, 2127, 110, 766, 1123, 183, 85], [28, 271, 6, 7238, 72, 881, 6, 42, 50, 2061, 34, 314, 1754, 91, 285, 36, 6, 70], [135, 222, 488, 267, 222, 3, 8, 4, 2234, 1, 326, 3, 222, 156, 21, 1128, 249, 3, 195, 10, 13, 6653, 2277], [38, 74, 1330, 89, 1375], [73, 58, 44, 1324, 85, 893, 2, 10, 331], [73, 308, 59, 16, 10], [38, 92, 1, 61, 143, 21, 39, 2480, 650, 791], [5925, 6, 25, 1915, 373], [1127, 24, 1350, 30, 4, 55, 305, 24, 95, 273, 2, 2859, 233, 975], [38, 1358, 1, 369, 895, 138, 21, 54, 117, 483, 150, 528, 929, 2, 257, 481, 71, 1164, 1522, 141, 111, 5412, 8, 348, 54, 185, 5, 167, 713], [246, 11, 63, 48, 621, 21, 68, 1, 265, 13, 129, 7, 281, 170, 7, 127, 21, 3, 184, 126, 309, 3111, 1, 168, 3, 707, 4, 1740, 421], [155, 243, 155, 18, 11, 153], [288, 226, 82], [1, 95, 1849, 60, 4, 850, 572, 444, 205], [122, 1574, 1, 63, 3, 1, 134, 2, 97, 1, 393, 29, 13, 5812, 7, 2550, 2, 204, 3, 444, 11, 3582, 516, 1, 70, 3, 1, 76, 3, 1, 993, 3], [63, 3, 1953, 63, 6, 395], [155, 263, 37, 8, 1483], [119, 233, 233, 7252, 639], [67, 34, 4137, 35, 460, 7, 251, 1, 33, 898, 6, 34, 158, 261, 7, 5, 15, 6000, 87, 501], [55, 487, 48, 20, 3], [236, 625, 39, 629, 100, 258, 1213, 863, 39, 20], [102, 700, 231, 9, 258, 153, 2, 7934, 744, 100, 4026], [143, 103, 496], [1173, 447, 21, 229, 4, 634], [39, 17, 2, 179, 65], [22, 292, 78, 2, 5008, 13, 5490], [79, 166, 3, 8, 5], [246, 115, 20, 78, 2, 5, 1725, 642, 29, 411, 25, 581, 58, 110, 26, 65, 3773, 47], [47, 1, 432, 16, 26, 1142, 111, 75, 1, 53, 52, 20, 5760, 10, 1, 61, 4, 12, 52], [119, 106, 88, 384, 166, 314, 68], [338, 1, 17, 107, 243, 8, 1739, 1529, 12, 5, 1493, 335, 1097, 7, 134, 2, 436, 4, 44, 43, 717, 1, 1017, 14, 211, 30, 15, 10, 2, 83, 200, 3, 140, 29, 131, 377, 2, 522, 7, 256, 180, 1, 475, 437, 42, 1, 1815, 61, 8, 4, 7, 432, 30, 558, 2, 436, 5, 717, 41, 460, 11, 2341, 129, 2406, 15, 316, 28, 3, 98, 271, 182], [4926, 1, 24, 65, 9, 66, 4078, 5398, 231, 1, 28, 66, 520, 21, 4078, 150, 4887], [84, 79, 16, 101], [118, 141, 1904, 12, 371, 68, 178, 141, 58, 8, 4, 248, 153, 274, 3, 302, 57, 5, 2574, 3664, 7, 1107, 13, 1318, 29, 5, 1046, 1046, 3665, 233, 975], [60, 979, 287, 8, 44, 43, 7318, 85, 1849, 1908], [1, 104, 36, 74, 3710, 59, 60, 164, 1351, 12, 100, 267], [84, 37, 578, 5, 167, 15, 11, 1797, 51, 42], [3, 53, 515, 267, 1710, 175, 3991, 9, 52, 39, 53, 39, 91, 29], [47, 2520, 30, 47, 1, 369], [84, 79, 16, 101], [28, 3, 310, 35, 10], [46, 500, 352, 100, 765, 461, 2560, 37, 69, 5, 329, 172, 2, 4282, 22, 275, 175, 133, 139, 4283, 250, 199], [60, 1946, 36, 36, 362, 153, 59, 60, 345, 12, 136, 2, 1390, 14], [1111, 149, 49, 2, 4275, 7, 1287], [194, 98, 16, 4515, 50, 4, 406, 690, 159, 26, 4, 40, 277, 619, 494, 175, 307, 620, 364, 343, 4516, 4517, 259], [27, 6, 622, 48, 19, 67, 3166, 444, 19], [816, 129, 118, 118], [115, 819, 478, 2, 2422, 5], [5, 447, 44, 43, 144, 962, 415, 44, 43, 44, 62, 43, 61, 79, 634, 294, 7, 69, 3, 213, 142], [31, 78, 12, 965, 33, 125, 3, 226, 44, 43, 210], [220, 1, 33, 58, 54, 44, 43, 210], [1439, 74, 400, 9, 1728, 29, 10, 36, 85, 144, 621, 850, 60, 11, 1466, 1439, 546, 91, 11, 1466, 42, 15, 136, 15, 280, 1752, 517, 4673, 373, 618], [64, 14, 200, 6, 1714], [180, 116, 1, 491, 42, 18, 11, 1115, 43], [922, 182, 2, 4, 55, 262, 6, 17, 212, 5, 802, 445, 596, 171, 19, 128, 9, 429, 37, 16, 22, 66, 534, 228, 738, 399, 585, 418], [150, 11, 138, 347, 384, 291, 464, 88, 6, 2274, 548, 743, 384, 49, 958, 88, 38, 314, 242, 2, 49, 339], [111, 2226, 1, 28, 32, 105], [1, 3123, 117, 483, 19, 133, 6, 21, 545, 1, 186, 280, 432, 6, 648, 155, 1570], [1014, 9, 36, 5, 1507, 2135, 9, 624, 29, 167, 115, 188, 5, 1715, 1539, 12, 29, 7353, 418], [1, 95, 17, 111, 15, 13, 5398, 8, 11, 1406, 1, 64, 8, 138, 45, 3, 358, 10, 1, 5399, 97, 3, 36, 1, 184, 187, 8, 11, 340], [112, 33, 16, 105], [45, 20, 3, 78, 2, 1833, 13], [105, 437, 35, 10, 1, 432, 169, 187, 314, 59, 3, 552], [84, 79, 16, 101], [106, 106, 31, 190, 281, 45, 33, 3, 1390, 5, 917], [106, 312, 656, 390, 59, 51, 156, 1, 76, 1579, 105, 67, 14, 2, 11, 489, 582, 390], [3, 149, 32, 120, 3222, 36, 3, 70, 1256, 564, 126, 1, 94, 53, 83], [246, 2276, 48, 20, 3, 89, 1, 211, 63, 2, 17, 4, 255, 180, 95, 3, 97, 10, 51, 3, 393, 57, 7, 51, 3, 20, 8, 2, 526], [1256, 146, 4, 1446, 121, 3, 49, 211, 30, 120], [730, 81, 16, 2, 38, 7642, 128, 13, 1731, 15, 152, 566, 310, 62, 2, 318, 50, 13, 108, 22, 7643, 3851, 1184, 7644, 259, 82, 7645], [129, 5, 1578, 8, 131, 24, 60, 20, 131, 3, 76, 4, 370, 2, 1145, 60, 20, 24, 52, 8, 52, 60, 4, 131, 242, 5, 735, 412, 9, 1, 560, 77], [194, 39, 20, 296, 2, 221, 6, 611, 297, 367, 21, 3, 17, 212, 4, 1144, 171, 272, 16, 5578, 50, 682, 300, 128, 5579, 3460, 66], [31, 841, 15, 35, 3, 83, 41, 113, 150, 113, 27, 51, 3, 70, 7, 50, 22, 18, 79, 27, 5, 268], [608, 19, 96, 1693, 1694, 91, 492, 16, 2860, 22, 1695, 609, 34, 828, 319, 1696, 679, 1697, 2861, 472, 1698, 1699, 1297, 1298, 1299, 196], [322, 31, 29, 11, 1625, 159, 55, 721, 39, 1943, 42, 4], [1, 61, 29, 4, 931, 35, 1883, 6440], [328, 3, 20, 324, 4, 1515, 1163, 328, 16, 2104, 2105, 406, 536, 973, 1516, 344], [71, 1164, 6, 28, 16, 10, 523, 502, 950], [767, 31, 23, 2884, 1, 701, 5767, 92, 2252, 586], [121, 29, 222, 846, 137], [732, 281, 99, 2620], [505, 427, 22, 88, 1, 537, 1567, 66], [312, 30, 65, 18, 44, 43, 47], [55, 178, 29, 5, 4889, 613, 5, 66, 1014, 31, 42, 29, 41, 483], [194, 39, 20, 296, 2, 221, 3, 167, 1292, 297, 367, 21, 3, 17, 212, 4, 1461, 171, 272, 16, 128, 469, 510, 689, 66], [20, 3, 2475, 154, 22], [112, 20, 3, 687, 1, 64, 662, 112], [591, 13, 16, 3, 293, 80, 11, 1214, 635], [55, 232, 9, 83, 5, 305, 141, 2, 4, 21, 5, 1884, 33, 1824, 7, 318, 36, 3, 70, 2, 53, 120], [48, 58, 93, 28, 32, 14, 149, 177, 391, 2, 369, 743], [354, 24, 39, 386, 530, 6, 211, 169, 181, 6, 5011, 24, 39, 225, 3743, 1798, 1798, 386, 225, 54, 160, 829, 25, 89, 23, 78, 54, 386, 16, 88], [9, 65, 276, 708, 9, 257, 12, 2445, 27, 3, 32, 111, 721, 50, 13, 138, 242], [217, 141, 2590, 100, 674, 238, 7, 951, 13, 108, 311, 115, 749, 3, 2, 184, 54, 135, 14, 9, 16, 50, 4, 406], [369, 51, 1111, 3, 53, 7637, 3, 332, 184, 54, 135, 14, 9, 140, 205, 4, 16, 18, 50, 406, 196, 210, 275], [114, 1, 94, 17, 99, 145, 7, 19, 60, 245, 30, 4, 7624, 467, 8, 5, 808, 7, 852, 2488, 23, 32, 36, 256, 1020], [290, 88, 643, 19, 2987, 151, 62, 6, 276], [290, 2458, 8, 11, 315, 2459, 3, 2460, 34, 1262, 2461, 34, 302, 1605, 34, 2462, 1858, 34, 1958, 486, 34, 237, 7, 337, 34, 764, 552, 55, 178, 112], [1276, 54, 65, 5, 2014, 920, 217, 104, 8, 15, 6, 126, 121, 54, 65, 121, 718, 58, 525, 6044, 163, 360, 718], [84, 79, 16, 101, 8, 285], [13, 154, 79, 132, 5, 2103, 154, 22], [1, 63, 3, 612, 137], [2056, 1, 169, 111, 748, 35, 3355, 54, 5, 370], [1, 33, 109, 186, 15, 349, 1, 33, 271], [32, 10, 54, 15, 41, 11, 1338, 746, 2, 58, 2, 1934], [11, 103, 496, 630, 64, 47, 1, 225, 2, 4, 931, 35, 11, 6311, 135, 9, 41, 3505, 59, 122], [27, 3, 6674, 21, 8, 83, 4744, 496, 895, 17, 4853, 15, 833, 1681, 1534, 218, 35], [3], [182, 14, 64, 66, 50, 24, 391, 192, 52, 785, 22, 437, 216], [], [91, 73, 78, 40, 1527, 285], [11, 1293, 442, 64, 23, 558, 2, 17, 1403, 27, 3, 70, 1403, 75, 68], [119, 47, 1, 475, 53, 51, 3, 860, 1069, 1, 61, 353], [37, 195, 14, 25, 51, 753, 15, 514, 27, 3, 57], [70, 19, 32, 2411, 215, 70, 342, 1624, 2355, 195, 1236, 19, 34, 538, 474, 5, 1892, 3215, 1624, 409, 399, 1243, 2, 7196, 944, 2412, 7929, 125, 196], [979, 527, 318, 1287, 3722, 8, 4, 2568, 190, 109, 19, 5029], [102, 818, 1, 127, 3, 134, 4, 192, 118, 1, 265, 1, 134, 58, 198, 220, 2, 80, 3, 63, 3124, 5484, 1, 70, 2013, 888, 7, 1, 70, 4, 502, 325, 5819, 6550], [1371, 7, 703, 332, 1104], [452, 117, 2099, 7, 211, 1824, 50, 5, 1782, 564, 38, 342, 1, 37, 95, 57, 1413, 1306, 115, 95, 76, 24, 38], [47, 133, 73, 59], [102, 116, 6, 1275, 515, 19, 32, 40, 203, 2062, 36, 2

In [24]:
len(x_train_new)

4457

In [25]:
len(x_test_new)

1115

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [27]:
max_length = 50
x_train_padding = pad_sequences(x_train_new, maxlen = max_length)

In [28]:
x_test_padding = pad_sequences(x_test_new, maxlen = max_length)

In [30]:
print(x_train_padding)

[[   0    0    0 ...    2  316  238]
 [   0    0    0 ...    3   53 2604]
 [   0    0    0 ...    6  247   99]
 ...
 [   0    0    0 ...  254   31 2486]
 [   0    0    0 ... 1197    1  247]
 [   0    0    0 ...    9 3219 1396]]

In [31]:
print(x_test_padding)

[[   0    0    0 ...  267 2214    6]
 [   0    0    0 ...  588   12 2575]
 [   0    0    0 ...   19   55 1549]
 ...
 [   0    0    0 ...    3   25  123]
 [   0    0    0 ...  109  186  663]
 [   0    0    0 ...  415  761   91]]

In [32]:
from tensorflow.keras.models import Sequential

In [33]:
from tensorflow.keras.layers import Dense ,SimpleRNN,Embedding

In [41]:
model = Sequential()
model.add(Embedding(input_dim=8000, output_dim=128,input_length = max_length))

In [42]:
model.add(SimpleRNN(32))
model.add(Dense(1,activation="sigmoid"))

In [43]:
model.compile(loss="binary_crossentropy",
              optimizer = "adam",
              metrics = ["accuracy"])

In [44]:
model.fit(x_train_padding,y_train,epochs=10,validation_data=(x_test_padding,y_test),batch_size=32)

Epoch 1/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8988 - loss: 0.2844 - val_accuracy: 0.9587 - val_loss: 0.1380
Epoch 2/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.9908 - loss: 0.0393 - val_accuracy: 0.9821 - val_loss: 0.0668
Epoch 3/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.9987 - loss: 0.0088 - val_accuracy: 0.9857 - val_loss: 0.0614
Epoch 4/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.9996 - loss: 0.0047 - val_accuracy: 0.9848 - val_loss: 0.0632
Epoch 5/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9998 - loss: 0.0025 - val_accuracy: 0.9857 - val_loss: 0.0632
Epoch 6/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9848 - val_loss: 0.0538
Epoch 7/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 9.4711e-04 - val_accuracy: 0.9865 - val_loss: 0.0610
Epoch 8/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 6.9750e-04 - val_accuracy: 0.9857 - val_loss: 0.0604
Epoch 9/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 1.0000 - loss: 5.3255e-04 - val_accuracy: 0.9857 - val_loss: 0.0621
Epoch 10/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 4.2277e-04 - val_accuracy: 0.9857 - val_loss: 0.0630

In [45]:
model.evaluate(x_test_padding,y_test)

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9857 - loss: 0.0630

[0.06301591545343399, 0.9856502413749695]

In [46]:
user_input = ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]

In [47]:
user_input_token = tokens.texts_to_sequences(user_input)

In [48]:
user_padding = pad_sequences(user_input_token,maxlen=max_length)

In [49]:
predict = model.predict(user_padding)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step

In [51]:
predict

array([[0.99896324]], dtype=float32)

In [52]:
if predict[0][0]>0.5:
  print("spam")
else:
  print("ham")

spam